Normalize f-strings across code base
rootstrap/django-drip-campaigns pull request #58
Opened 2020-10-12 17:53 UTC by markrofail

close #41

This PR removes old `% string formating` and `str.format` in favor of `f-strings`

Except for:
[this snippet](https://github.com/markrofail/django-drip-campaigns/blob/5d8073a8640cc3978c2072976624660a7d7ee474/drip/helpers.py#L8)
```python
def STRFDATETIME_REPL(x):
    return '%%(%s)s' % x.group()
```
I don't understand it, my best shot was `return f"%{x.group()['%s']}"`

2020-10-12 17:57 UTC, markrofail commented
CI fails on Python `3.5` build, since f-strings were introduced in `3.6`
![image](https://user-images.githubusercontent.com/15761271/95776726-2d1e8e80-0cc5-11eb-9a98-0a46cf8b331e.png)

2020-10-12 19:05 UTC, brunomichetti commented
> close #41
> 
> This PR removes old `% string formating` and `str.format` in favor of `f-strings`
> 
> Except for:
> [this snippet](https://github.com/markrofail/django-drip-campaigns/blob/5d8073a8640cc3978c2072976624660a7d7ee474/drip/helpers.py#L8)
> 
> ```python
> def STRFDATETIME_REPL(x):
>     return '%%(%s)s' % x.group()
> ```
> 
> I don't understand it, my best shot was `return f"%{x.group()['%s']}"`

I think that is `return f'%({x.group()})s'`.
Don't you think?

2020-10-12 19:11 UTC, markrofail commented
> > close #41
> > This PR removes old `% string formating` and `str.format` in favor of `f-strings`
> > Except for:
> > [this snippet](https://github.com/markrofail/django-drip-campaigns/blob/5d8073a8640cc3978c2072976624660a7d7ee474/drip/helpers.py#L8)
> > ```python
> > def STRFDATETIME_REPL(x):
> >     return '%%(%s)s' % x.group()
> > ```
> > 
> > 
> > I don't understand it, my best shot was `return f"%{x.group()['%s']}"`
> 
> I think that is `return f'%({x.group()})s'`.
> Don't you think?

I think you are right

2020-10-13 13:47 UTC, kaozdl commented
hey @markrofail thanks for contributing!
I failed to notice that fstrings were introduced in python 3.6
Since we want to support all posible installations of django 2.2 and further we cannot drop support for python 3.5

What you can do is use format this way if you want to have fstring-like styntax while remaining compatible
```
"Hello {name}".format(**locals())
```

2020-10-13 17:50 UTC, brunomichetti requested changes
Thanks @markrofail for contributing!!
If you applied the syntax `'Hello {name}'.format(**locals())` on every occurrence as @kaozdl says, we can close the issue and keep the compatibility with python 3.5
Thanks again!

2020-10-13 17:59 UTC, markrofail commented
> Thanks @markrofail for contributing!!
> If you applied the syntax `'Hello {name}'.format(**locals())` on every occurrence as @kaozdl says, we can close the issue and keep the compatibility with python 3.5
> Thanks again!

I honestly don't like this. You can check some reasoning [here](https://stackoverflow.com/questions/1550479/python-is-using-vars-locals-a-good-practice). I would prefer switching to str.format with named placeholders. Like so 

```python
'Hello {name}'.format(name=name)
```
since we are not always sure what `locals()` contains

2020-10-13 18:17 UTC, markrofail commented
I look at the code one more. I dont think the 
```python
"Hello {name}".format(**locals())
```
pattern will work. Because of strings like 
```python
"Failed to send drip {self.drip_model.id} to user {str(user)}: {str(e)}"
```
I don't know what `self` would unify with. Again. I am afraid of `locals()` behaviour.

If still you prefer this pattern I will commit it. I switched to `str.format` till then

2020-10-13 19:02 UTC, brunomichetti commented
> I look at the code one more. I dont think the
> 
> ```python
> "Hello {name}".format(**locals())
> ```
> 
> pattern will work. Because of strings like
> 
> ```python
> "Failed to send drip {self.drip_model.id} to user {str(user)}: {str(e)}"
> ```
> 
> I don't know what `self` would unify with. Again. I am afraid of `locals()` behaviour.
> 
> If still you prefer this pattern I will commit it. I switched to `str.format` till then

Thanks for explaining that!
Ok we agree to use the option that you propose: `'Hello {name}'.format(name=name)`
Thanks!

2020-10-13 20:08 UTC, brunomichetti commented on drip/drips.py
> +                email=self.drip_base.from_email
Please put a comma at the end of this line

2020-10-13 20:08 UTC, brunomichetti commented on drip/drips.py
> +                        err=str(e)
A comma here too

2020-10-13 20:09 UTC, brunomichetti commented on drip/models.py
> +                    error=str(e)
Here a comma too

2020-10-13 20:10 UTC, brunomichetti commented on drip/models.py
> +            field_name = "num_{agg}".format(agg=agg.replace('__', '_'))
Please use single quotes around `num_{agg}`

2020-10-13 20:11 UTC, brunomichetti approved these changes
Left a couple of minor comments.
👏

2020-10-13 20:12 UTC, markrofail commented
> Left a couple of minor comments.

Done :+1:

2020-10-13 20:14 UTC, kaozdl commented
Thanks!
Will merge when CI passes :)

2020-10-13 20:50 UTC, merged