Feature/travis release
rootstrap/django-drip-campaigns pull request #74
Opened 2020-11-09 14:55 UTC by brunomichetti

2020-11-09 19:53 UTC, nsantos16 commented on CONTRIBUTING.md
> +- If you are doing a breaking changes or a very big feature, then bump the first digit.
I think we need to define a better way to establish the version releases(in my opinion semantic versioning fits for this project).
Here's a couple of references:
- [Maintaining Open Source Projects: Versioning and Releasing](https://thoughtbot.com/blog/maintaining-open-source-projects-versioning#time-based-releases)
- [Semantic versioning](https://semver.org/)
@rootstrap/python-maintainers

2020-11-10 20:29 UTC, kaozdl submitted a review, later dismissed

2020-11-11 14:14 UTC, kaozdl approved these changes

2020-11-11 14:15 UTC, kaozdl requested changes
Shouldn't this be saved somewhere?

2020-11-11 14:25 UTC, brunomichetti commented
> Shouldn't this be saved somewhere?

What do you mean?

2020-11-11 17:31 UTC, kaozdl approved these changes

2020-11-16 13:03 UTC, jiss2891 reviewed
Left a comment

2020-11-16 13:03 UTC, jiss2891 commented on .travis.yml
> +        username: brunomichetti
Do we really want to keep this info on the repo?

2020-11-16 13:08 UTC, jiss2891 commented on .travis.yml
> +        username: brunomichetti
we should manage this through environment variables.

2020-11-16 19:40 UTC, kaozdl approved these changes

2020-11-16 19:43 UTC, jiss2891 approved these changes

2020-11-16 19:44 UTC, merged